#!perl

use Modern::Perl 1.20150127;
use App::PrettyDamQuick;
use Try::Tiny 0.24;

my @args = @ARGV;
my $command = shift @args || 'help';

if ( App::PrettyDamQuick->can($command) ) {
    try {
        App::PrettyDamQuick->$command(@args);
    }
    catch {
        say($_);
    };
}
else {
    say("$command is not a command");
    App::PrettyDamQuick->help;
}
1;
