#!perl

use Modern::Perl;
use App::PrettyDamQuick;
use Try::Tiny;

my @args = @ARGV;
my $command = shift @args || 'help';

if (App::PrettyDamQuick->can($command)) {
	try {
		App::PrettyDamQuick->$command(@args);
	}
	catch {
		system('cowsay', '-d', $_);
	};
}
else {
    system('cowsay', "$command is not a command");
    App::PrettyDamQuick->help;
}
1;
